# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'flipper' do
pod 'Parse', '~> 1.12'
pod 'ParseFacebookUtilsV4', '~> 1.11'
pod 'ParseTwitterUtils', '~> 1.10'
pod 'FBSDKLoginKit', '~> 4.9'
pod 'FBSDKCoreKit', '~> 4.9'
pod 'FHSTwitterEngine', '~> 2.0'
end

target 'flipperTests' do

end

target 'flipperUITests' do

end

