# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'flipper' do
pod 'Parse', '~> 1.12'
end

target 'flipperTests' do

end

target 'flipperUITests' do

end

